### ISSUE TITLE
Live counter for kampchat

### ISSUE THREAD

**Issue by glennlunder** [geirawsm/sausage_bot#18]
Vi har ett problem når vi henger i kampchat med at folk streamer fra forskjellige steder, eller ser på tv på forskjellige løsninger så er ikke streamene 100% synkronisert. Det betyr at i går for eksempel kom det en kar inn i chatten som lå 30 sek før oss (så nok på direkte tv, web har litt delay), og det ødela litt når han sa "Å neeeei, faen ass" 30 sekunder før vi andre kunne se hva som skjedde. Det jeg ønsker meg er: En slags live count hvor en admin kan låse inn tida og så tikker det fremover gjennom omgangen. Så kan folk pause og synke til med det.

Så, kanskje !streamtime 01:10

Og når du trykker enter så teller den derifra og oppover til vi skriver !streamtime stop

**Comment by geirawsm** [comment]
Fra [Discord API documentation](https://discord.com/developers/docs/topics/rate-limits):
`All bots can make up to 50 requests per second to our API. This is independent of any individual rate limit on a route. If your bot gets big enough, based on its functionality, it may be impossible to stay below 50 requests per second during normal operations.`

Så det kan bli litt risky å lage det som en spesifikk funksjon som teller hvert eneste sekund. Kanskje en løsning blir å lage en som oppdaterer hvert 10 sekund eller så. Må sjekke åssen dette kan gjøres.

**Comment by glennlunder** [comment]
Må dette gjøre noen requests i det hele tatt da, utover å telle tid? Kan ikke se hva det må interface med, egentlig?

Subsidiært, kunne man streame nedtellinga inn som gif/video? :D Eller bare en tekstfil der man viser neste linje (som er neste sekund) en gang per sekund. Må da være mange måter å løse dette på.

**Comment by geirawsm** [comment]
Det gjøres en request mot discord-apiet ganske ofte i scriptet, og begrensninga på 50 i sekunder gjelder også for andre funksjoner som kjører.
Jeg vurderte en liten nettside som kjører i flask som kunne serve en "oppteller" i dette tilfellet, men en gif tror jeg funker like bra! Skal se om det går an å få til noe som kan tilpasses på noe vis.

**Comment by geirawsm** [comment]
9fde89f641f814991f20bf9f606cdd6c9b9d035e
